modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "${mod_issue_tracker}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_repository}"
authors = "${mod_authors}"
description = '''${mod_description}'''
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "sfm"
mandatory = true
versionRange = "${sfm_version_range}"
ordering = "AFTER"

[[dependencies.${ mod_id }]]
modId = "thermal_expansion"
mandatory = true
versionRange = "${thermal_version_range}"
ordering = "BEFORE"
